language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

before_script:
  - cd client
  - yarn install
  - gem install coveralls-lcov
  
script:
  - yarn run flow src/
  - yarn test --coverage

after_script:
  - yarn run build  
  - coveralls-lcov coverage/lcov.info
