language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

before_script:
  - cd client
  - yarn install
  - gem install coveralls-lcov
  
script:
  - yarn run test:lint
  - yarn run test:unit --coverage

after_success:
  - yarn run build  

after_script:
  - coveralls-lcov coverage/lcov.info
