// flow-typed signature: d55b2aca0853f787e126ed28aa3399a2
// flow-typed version: <<STUB>>/@firebase/app-types_v^0.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/app-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/app-types' {
  declare module.exports: any;
}
